name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: corepack enable && yarn
      - name: publish
        run: yarn pub
