name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  YARN_ENABLE_IMMUTABLE_INSTALLS: false
jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: corepack enable && yarn
      # - name: publish
        # run: yarn pub
